### ISSUE TITLE
Impossible to add a generic camera with auth

### ISSUE THREAD

**Issue by brunetton** [maikito26/plugin.video.surveillanceroom#1]
Hi,

I'm very interested in using surveillanceroom. I love the idea !
I have a D-LINK DCS-933L with auth and I can't figure how to access the stream : when I select "generic IP camera", the username/password is disabled.
Is it possible to use a generic camera with auth ?

Thanks !

**Comment by maikito26** [comment]
Yes!   I use a DCS-932L so it should be similar.   Although it only works for MJPEG.  You would pass credentials in the URL as such:

 

http://username:password@ipaddress:port/...

 

If you’re using the snapshot feature, you will need to disable authentication for snapshots within the DCS-933L settings.  I haven’t figured out how to get around it otherwise.
